## הגדרות ומקדים

### ספריות

In [1]:
import os
import sys
import pandas as pd
import geopandas as gpd

In [2]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.float_format', lambda x: '%.3f' % x)

### העלת משתנים להרצת הקוד

In [3]:
cwd = os.getcwd()

create_forecast_basic_folder_path = os.path.dirname(cwd)

sys.path.append(create_forecast_basic_folder_path)

## פונקציות

### פונקציות גלובליות

In [4]:
from global_functions import up_load_shp, up_load_df, drop_geo, up_load_gdb

## להריץ תלמידים

In [5]:
%run "students_current_year.ipynb"

C:\Users\dpere\AppData\Local\Temp\ipykernel_15148\2539747398.py:3: FutureWarning: The provided callable <built-in function sum> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  student_arab_not_gov=student_arab_not_gov.pivot_table(index='Taz_num',aggfunc=sum)[['num_student']]
C:\Users\dpere\AppData\Local\Temp\ipykernel_15148\2039466339.py:1: FutureWarning: The provided callable <built-in function sum> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  taz['student_chardi_not_gov']=drop_geo(student_chardi_not_gov_with_taz).pivot_table(index='Taz_num',aggfunc=sum)[['num_students']]
C:\Users\dpere\AppData\Local\Temp\ipykernel_15148\2892090057.py:1: FutureWarning: The provided callable <built-in function sum> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  uni_students_sum_by_taz=uni_students_with_taz[col].pivot_table(index='Taz_num',aggfunc=sum).reset_index()
C:\Users\dpere\AppData\Local\Temp\ipykernel_15148\997828904.py:1: FutureWarning: The provided callable <built-in function sum> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  student_yeshiva_by_gender_taz=drop_geo(student_yeshiva).pivot_table(index=['Taz_num','gender'],aggfunc=sum).reset_index()
C:\Users\dpere\AppData\Local\Temp\ipykernel_15148\709779699.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ 35.15       276.         300.08391068   8.1       ]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  taz.loc[(taz['main_secto']=='U_Orthodox')&(taz['kollim_demand']>taz['Yeshiva']),'add_from_kollim_demand']=taz['kollim_demand']-taz['Yeshiva']

## להעלות שכבות

In [6]:
path=r'{}\background_files\EMP_KIBOLET.gdb'.format(cwd)

EMP_kibolet=up_load_gdb(path,'EMP_kibolet')

In [7]:
EMP_kibolet=EMP_kibolet.fillna(0)

EMP_kibolet['emp_without_palestin']=EMP_kibolet['kayim_emp']-EMP_kibolet['Palestinians']

emp_without_palestin_not_okev=EMP_kibolet['emp_without_palestin'].sum().item()

emp_Education=taz.query('main_secto!="Palestinian"')['emp_Education'].sum().item()

## הוספת סטודנטים לאוכלוסיה ולהתפלגות גילים

In [8]:
student_dorms=up_load_shp(r'{}\background_files\student_dorms.shp'.format(cwd))

In [9]:
#העלה של נתוני אנשים התפלגות גילים שנוצר לפני הקוד הזה
path=r'{}\Intermediates'.format(cwd)
taz_with_pop=up_load_df(path,'taz_with_pop_info')

In [10]:
col_needed=['Taz_num','aprt_20',
 'pop',
 'pop_0',
 'pop_10',
 'pop_15',
 'pop_20',
 'pop_25',
 'pop_30',
 'pop_35',
 'pop_40',
 'pop_45',
 'pop_5',
 'pop_50',
 'pop_55',
 'pop_60',
 'pop_65',
 'pop_70',
 'pop_75up', 'hh_size']

In [11]:
taz=taz.merge(taz_with_pop[col_needed],on='Taz_num',how='left')

In [12]:
taz=taz.set_index('Taz_num')

In [13]:
taz['student_dorms']=gpd.sjoin(taz[['geometry']].reset_index(),student_dorms)[['Taz_num','student_nu']].pivot_table(index='Taz_num',aggfunc='sum')

In [14]:
taz=taz.fillna(0)

taz['pop_without_dorms_yeshiva']=taz['pop']

taz['pop']=taz['pop']+taz['student_dorms']

taz['pop_20_just_from_aprt']=taz['pop_20']

taz['pop_25_just_from_aprt']=taz['pop_25']

taz['pop_20']=taz['pop_20']+taz['student_dorms']*0.6

taz['pop_25']=taz['pop_25']+taz['student_dorms']*0.4

In [15]:
col=['pop_0',
 'pop_10',
 'pop_15',
 'pop_20',
 'pop_25',
 'pop_30',
 'pop_35',
 'pop_40',
 'pop_45',
 'pop_5',
 'pop_50',
 'pop_55',
 'pop_60',
 'pop_65',
 'pop_70',
 'pop_75up',]

taz['pop_check']=round(taz[col].sum(axis=1)-taz['pop'])

taz.loc[taz['main_secto']!="Palestinian"].loc[taz['pop_check']!=0]

Empty GeoDataFrame
Columns: [Taz_name, jeru_metro, in_jerusal, main_secto, SCHN_NAME, ENG_NAME_n, zonetype, Muni_Heb, Sug_Muni, CR_PNIM, highBusine, SCHOOLDIST, Urban, EIProp, poly_puma, F3, F2, F1, agri, Indus, Com_hotel, Business, Public, commuting, ieold, IEProp, perScaled, FreeBuffer, PaidBuffer, Rest_EmpBu, searchtime, walktime, cost, Agg_taz_nu, area, CITYCODE1, CITYCODE2, CITYCODE3, CITYCODE4, codeseq, codeseqCon, county, majunivenr, parktot, superZone, Taz1, slope, REGION, yosh, jerusalem_, geometry, SEA1, SEA2, SEA3, UOA1, UOA2, UOA3, ARA1, ARA2, ARA3, student_chardi_not_gov, student_arab_not_gov, TOA1, TOA2, TOA3, sector_for_chinuc, student, Univ_AR, Univ_SE, Univ_UO, emp_uni, univ, UNIVENRORTHFEMALE, UNIVENRORTHMALE, yeshiva_dorms_pop_15, yeshiva_dorms_pop_20, yeshiva_dorms_pop_25, yeshiva_dorms_pop_sum, emp_from_Yeshiva_student, Yeshiva, Seminar_dorms_pop_15, Seminar_dorms_pop_20, Seminar_dorms_pop_25, Seminar_dorms_pop_sum, emp_from_Seminar_student, Seminar, kollim_demand, add_from_kollim_demand, student_yeshiva_and_kollim, UO_Hi_Ed, emp_UO_Hi_Ed, jew, emp_from_student, emp_Education, aprt_20, pop, pop_0, pop_10, pop_15, pop_20, ...]
Index: []

## הוספת תלמידי ישיבה (באזורים חרדיים) אל כמות אוכלוסיה,התפלגות גילים

In [16]:
taz['pop_15_just_from_aprt']=taz['pop_15']

In [17]:

taz.loc[taz['main_secto']=="U_Orthodox",'pop']=taz['pop']+taz['yeshiva_dorms_pop_sum']

taz.loc[taz['main_secto']=="U_Orthodox",'pop_15']=taz['pop_15']+taz['yeshiva_dorms_pop_15']

taz.loc[taz['main_secto']=="U_Orthodox",'pop_20']=taz['pop_20']+taz['yeshiva_dorms_pop_20']

taz.loc[taz['main_secto']=="U_Orthodox",'pop_25']=taz['pop_25']+taz['yeshiva_dorms_pop_25']

In [18]:
col=['pop_0',
 'pop_10',
 'pop_15',
 'pop_20',
 'pop_25',
 'pop_30',
 'pop_35',
 'pop_40',
 'pop_45',
 'pop_5',
 'pop_50',
 'pop_55',
 'pop_60',
 'pop_65',
 'pop_70',
 'pop_75up',]

taz['pop_check']=round(taz[col].sum(axis=1)-taz['pop'])

taz.loc[taz['main_secto']!="Palestinian"].loc[taz['pop_check']!=0]

Empty GeoDataFrame
Columns: [Taz_name, jeru_metro, in_jerusal, main_secto, SCHN_NAME, ENG_NAME_n, zonetype, Muni_Heb, Sug_Muni, CR_PNIM, highBusine, SCHOOLDIST, Urban, EIProp, poly_puma, F3, F2, F1, agri, Indus, Com_hotel, Business, Public, commuting, ieold, IEProp, perScaled, FreeBuffer, PaidBuffer, Rest_EmpBu, searchtime, walktime, cost, Agg_taz_nu, area, CITYCODE1, CITYCODE2, CITYCODE3, CITYCODE4, codeseq, codeseqCon, county, majunivenr, parktot, superZone, Taz1, slope, REGION, yosh, jerusalem_, geometry, SEA1, SEA2, SEA3, UOA1, UOA2, UOA3, ARA1, ARA2, ARA3, student_chardi_not_gov, student_arab_not_gov, TOA1, TOA2, TOA3, sector_for_chinuc, student, Univ_AR, Univ_SE, Univ_UO, emp_uni, univ, UNIVENRORTHFEMALE, UNIVENRORTHMALE, yeshiva_dorms_pop_15, yeshiva_dorms_pop_20, yeshiva_dorms_pop_25, yeshiva_dorms_pop_sum, emp_from_Yeshiva_student, Yeshiva, Seminar_dorms_pop_15, Seminar_dorms_pop_20, Seminar_dorms_pop_25, Seminar_dorms_pop_sum, emp_from_Seminar_student, Seminar, kollim_demand, add_from_kollim_demand, student_yeshiva_and_kollim, UO_Hi_Ed, emp_UO_Hi_Ed, jew, emp_from_student, emp_Education, aprt_20, pop, pop_0, pop_10, pop_15, pop_20, ...]
Index: []

## כימות מועסקים במרחב צתאל

In [19]:
pre_woman=0.5

pre_man=1-pre_woman

In [20]:
work_age=[ 'pop_25',
 'pop_30',
 'pop_35',
 'pop_40',
 'pop_45',
 'pop_50',
 'pop_55',
 'pop_60']

under_work_age=[ 'pop_15', 'pop_20']

over_work_age=[ 'pop_65', 'pop_70', 'pop_75up']

In [21]:
taz['work_age']=taz[work_age].sum(axis=1)

taz['under_work_age']=taz[under_work_age].sum(axis=1)

taz['over_work_age']=taz[over_work_age].sum(axis=1)

In [22]:
sector='U_Orthodox'

taz.loc[taz['main_secto']==sector,'pop_emp']=taz['work_age']*pre_woman*0.75+taz['work_age']*pre_man*0.55
taz.loc[taz['main_secto']==sector,'pop_emp']=taz['pop_emp']+taz['under_work_age']*pre_woman*0.07+taz['under_work_age']*pre_man*0.09
taz.loc[taz['main_secto']==sector,'pop_emp']=taz['pop_emp']+taz['over_work_age']*pre_woman*0.05+taz['over_work_age']*pre_man*0.09

sector='Jewish'

taz.loc[taz['main_secto']==sector,'pop_emp']=taz['work_age']*pre_woman*0.9+taz['work_age']*pre_man*0.92
taz.loc[taz['main_secto']==sector,'pop_emp']=taz['pop_emp']+taz['under_work_age']*pre_woman*0.20+taz['under_work_age']*pre_man*0.15
taz.loc[taz['main_secto']==sector,'pop_emp']=taz['pop_emp']+taz['over_work_age']*pre_woman*0.2+taz['over_work_age']*pre_man*0.15

sector='Arab'

taz.loc[taz['main_secto']==sector,'pop_emp']=taz['work_age']*pre_woman*0.25+taz['work_age']*pre_man*0.7
taz.loc[taz['main_secto']==sector,'pop_emp']=taz['pop_emp']+taz['under_work_age']*pre_woman*0.2+taz['under_work_age']*pre_man*0.15
taz.loc[taz['main_secto']==sector,'pop_emp']=taz['pop_emp']+taz['over_work_age']*pre_woman*0.05+taz['over_work_age']*pre_man*0.09

sector='arabs_behined_seperation_wall'

taz.loc[taz['main_secto']==sector,'pop_emp']=taz['work_age']*pre_woman*0.25+taz['work_age']*pre_man*0.7
taz.loc[taz['main_secto']==sector,'pop_emp']=taz['pop_emp']+taz['under_work_age']*pre_woman*0.2+taz['under_work_age']*pre_man*0.15
taz.loc[taz['main_secto']==sector,'pop_emp']=taz['pop_emp']+taz['over_work_age']*pre_woman*0.05+taz['over_work_age']*pre_man*0.09

## חישוב אבטלה

In [23]:
taz['pop_emp_employed']=0

taz.loc[taz['main_secto']=="U_Orthodox",'pop_emp_employed']=taz['pop_emp']*0.97

taz.loc[taz['main_secto']=="Jewish",'pop_emp_employed']=taz['pop_emp']*0.98

taz.loc[taz['jew']==0,'pop_emp_employed']=taz['pop_emp']*0.95

C:\Users\dpere\AppData\Local\Temp\ipykernel_15148\219692974.py:3: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[8.53600000e-01 0.00000000e+00 2.77129000e+01 7.58928000e+01
 0.00000000e+00 0.00000000e+00 0.00000000e+00 3.54923000e+01
 2.69369000e+01 9.10830000e+00 5.25449000e+01 3.79852000e+01
 0.00000000e+00 3.81404000e+01 3.42410000e+00 3.82859000e+01
 2.68098300e+02 2.38911000e+01 3.50364000e+01 3.89455000e+01
 4.01774000e+01 2.07871000e+01 0.00000000e+00 5.24576000e+01
 9.88430000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 7.76000000e-02 0.00000000e+00
 2.32800000e-01 0.00000000e+00 0.00000000e+00 0.00000000e+00
 1.42493000e+01 0.00000000e+00 0.00000000e+00 0.00000000e+00
 3.68309000e+01 0.00000000e+00 3.93044000e+01 0.00000000e+00
 4.53863000e+01 1.70720000e+00 3.11370000e+00 0.00000000e+00
 4.49110000e+01 2.29599000e+01 1.54909000e+01 1.83718000e+01
 0.00000000e+00 0.00000000e+00 5.43200000e-01 0.00000000e+00
 5.43200000e-01 0.00000000e+00 7.76000000e-02 3.79076000e+01
 0.00000000e+00 3.60452000e+01 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 7.22650000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 3.17675000e+01
 3.92171000e+01 4.28158000e+01 0.00000000e+00 6.92871000e+01
 0.00000000e+00 0.00000000e+00 0.00000000e+00 6.29724000e+01
 1.33084000e+01 0.00000000e+00 1.52581000e+01 6.69300000e+00
 2.71600000e+00 7.73769000e+01 1.31920000e+00 5.76180000e+00
 1.28428000e+01 0.00000000e+00 0.00000000e+00 6.16532000e+01
 0.00000000e+00 2.70824000e+01 2.84889000e+01 0.00000000e+00
 1.60341000e+01 0.00000000e+00 0.00000000e+00 0.00000000e+00
 5.83940000e+00 3.81210000e+00 4.43290000e+00 0.00000000e+00
 0.00000000e+00 1.73630000e+01 3.71316000e+01 6.20800000e-01
 9.57390000e+00 0.00000000e+00 0.00000000e+00 7.76000000e-02
 4.21950000e+01 0.00000000e+00 1.61582600e+02 8.08204000e+01
 6.14980000e+00 5.48729000e+01 7.14017000e+01 3.10594000e+01
 8.56510000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 6.69300000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 6.92221100e+02 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 4.25830000e+01 1.06860879e+03 3.43612800e+02
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 2.24943000e+01
 0.00000000e+00 0.00000000e+00 5.76180000e+00 5.43200000e-01
 0.00000000e+00 0.00000000e+00 0.00000000e+00 2.33576000e+01
 0.00000000e+00 0.00000000e+00]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  taz.loc[taz['main_secto']=="U_Orthodox",'pop_emp_employed']=taz['pop_emp']*0.97

## חישוב יוממות

In [24]:
taz['pop_emp_employed_out_of_jtmt_area']=taz['pop_emp_employed']*taz['commuting']

emp_left_jtmt_area=taz['pop_emp_employed_out_of_jtmt_area'].sum().item()

round(emp_left_jtmt_area,-3)

37000.0

In [25]:
emp_from_jtmt_area=taz['pop_emp_employed'].sum().item()-emp_left_jtmt_area

emp_in_jtmt_area=emp_from_jtmt_area*1.07 #יוממות פנימה מחוץ למרחב

round(emp_in_jtmt_area,-3)

53000.0

In [26]:
emp_in_jtmt_area_without_mobile=emp_in_jtmt_area*0.95 #הפחחת עובדים ניידים

round(emp_in_jtmt_area_without_mobile,-3)

50000.0

In [27]:
emp_okev=emp_in_jtmt_area_without_mobile-emp_Education-emp_without_palestin_not_okev

## פיזור עוקב

In [28]:
EMP_kibolet['geometry_buff']=EMP_kibolet.buffer(250)

EMP_buffer=EMP_kibolet.set_geometry('geometry_buff').query('kayim_emp>0')

EMP_buffer=EMP_buffer.dissolve()[['geometry_buff']]

taz['taz_area']=taz.area

In [29]:
emp_buffer_taz=gpd.overlay(EMP_buffer,taz.reset_index())

emp_buffer_taz['emp_samll_area']=emp_buffer_taz.area

emp_buffer_taz['emp_pre_from_taz']=emp_buffer_taz['emp_samll_area']/emp_buffer_taz['taz_area']

In [30]:
taz_num_no_need_okev=emp_buffer_taz.loc[emp_buffer_taz['emp_pre_from_taz']>0.4].Taz_num.to_list()

In [31]:
taz['okev']=0
taz.loc[(~taz.index.isin(taz_num_no_need_okev))&(taz['pop']>0)&(taz['main_secto']!="Palestinia"),'okev']=1

taz.loc[taz['main_secto']=="arabs_behined_seperation_wall",'okev']=1

In [32]:
city_muni=['מודיעין עילית','בית שמש','ירושלים','מודיעין - מכבים - רעות']

## מקדם עוקב

In [33]:
okev_level=0.15

arab_city=taz.query('jew==0 & okev==1')['aprt_20'].sum().item()

arab_sub=0

ou_sub=taz.query('main_secto=="U_Orthodox" & ~Muni_Heb.isin(@city_muni) & okev==1')['aprt_20'].sum().item()

In [34]:
ou_city=taz.query('main_secto=="U_Orthodox" & Muni_Heb.isin(@city_muni) & okev==1')['aprt_20'].sum().item()

general_city=taz.query('main_secto=="Jewish" & Muni_Heb.isin(@city_muni) & okev==1')['aprt_20'].sum().item()

general_sub=taz.query('main_secto=="Jewish" & ~Muni_Heb.isin(@city_muni) & okev==1')['aprt_20'].sum().item()

base_okev_factor=(emp_okev-(okev_level*general_city-okev_level*(ou_sub+arab_city)-2*okev_level*arab_sub))/(general_sub+general_city+ou_city+ou_sub+arab_city+arab_sub)

base_okev_factor=round(base_okev_factor,3)

In [35]:
data = [['Jewish', base_okev_factor,base_okev_factor+okev_level],['arab', base_okev_factor-okev_level,base_okev_factor], ['U_Orthodox',base_okev_factor-2*okev_level,base_okev_factor-okev_level]]
 
# Create the pandas DataFrame
df = pd.DataFrame(data, columns=['sector', 'sub','city'])
okev_factor=df.set_index('sector')
okev_factor.to_excel(r'{}\Intermediates\okev_factor.xlsx'.format(cwd))

In [36]:
taz['emp_okev']=0

taz.loc[(taz['jew']==0)&(taz['okev']==1),'emp_okev']=taz['aprt_20']*okev_factor.loc['arab','city']

taz.loc[(taz['main_secto']=="U_Orthodox")&(~taz['Muni_Heb'].isin(city_muni))&(taz['okev']==1),'emp_okev']=taz['aprt_20']*okev_factor.loc['U_Orthodox','sub']

taz.loc[(taz['main_secto']=="U_Orthodox")&(taz['Muni_Heb'].isin(city_muni))&(taz['okev']==1),'emp_okev']=taz['aprt_20']*okev_factor.loc['U_Orthodox','city']

taz.loc[(taz['main_secto']=="Jewish")&(taz['Muni_Heb'].isin(city_muni))&(taz['okev']==1),'emp_okev']=taz['aprt_20']*okev_factor.loc['Jewish','city']

taz.loc[(taz['main_secto']=="Jewish")&(~taz['Muni_Heb'].isin(city_muni))&(taz['okev']==1),'emp_okev']=taz['aprt_20']*okev_factor.loc['Jewish','sub']

taz.emp_okev.sum().item()-emp_okev

C:\Users\dpere\AppData\Local\Temp\ipykernel_15148\1435860360.py:3: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[    -0.             -0.             -0.         -11635.64866814
     -0.         -17215.61078682 -10973.05516632 -10335.108
  -2984.73        -7324.52938563     -0.          -4420.27615026
  -1072.98787009   -717.39194022 -24842.67710029 -31964.3863003
   -135.79793411  -2805.43660252  -6966.41902264  -1283.17710303
  -1204.79272932  -3662.64109449  -3024.17890551]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  taz.loc[(taz['jew']==0)&(taz['okev']==1),'emp_okev']=taz['aprt_20']*okev_factor.loc['arab','city']

8019.243973950157

## פיצול שכבת לא עוקב לאזורי תנועה

In [37]:
EMP_kibolet['emp_area']=EMP_kibolet.area

EMP_kibolet['ID']=EMP_kibolet.index

EMP_kibolet_by_taz=gpd.overlay(taz.reset_index()[['Taz_num','taz_area','geometry']],EMP_kibolet)

EMP_kibolet_by_taz['small_area']=EMP_kibolet_by_taz.area

C:\Users\dpere\AppData\Local\Temp\ipykernel_15148\1806380584.py:5: UserWarning: `keep_geom_type=True` in overlay resulted in 279 dropped geometries of different geometry types than df1 has. Set `keep_geom_type=False` to retain all geometries
  EMP_kibolet_by_taz=gpd.overlay(taz.reset_index()[['Taz_num','taz_area','geometry']],EMP_kibolet)

In [38]:
EMP_kibolet_by_taz['pre_small_area_emp']=EMP_kibolet_by_taz['small_area']/EMP_kibolet_by_taz['emp_area']

EMP_kibolet_by_taz['pre_small_area_taz']=EMP_kibolet_by_taz['small_area']/EMP_kibolet_by_taz['taz_area']

EMP_kibolet_by_taz=EMP_kibolet_by_taz.query('(pre_small_area_taz >0.7) | (pre_small_area_emp >0.1)').drop(columns='geometry_buff')

EMP_kibolet_by_taz=EMP_kibolet_by_taz.set_index('ID')

In [39]:
EMP_kibolet_by_taz['id_area_for_pre']=EMP_kibolet_by_taz.reset_index().groupby(by='ID')['small_area'].sum()

EMP_kibolet_by_taz['prec_from_id']=EMP_kibolet_by_taz['small_area']/EMP_kibolet_by_taz['id_area_for_pre']

EMP_kibolet_by_taz['emp_without_palestin_in_taz']=EMP_kibolet_by_taz['emp_without_palestin']*EMP_kibolet_by_taz['prec_from_id']

taz['emp_not_okev']=drop_geo(EMP_kibolet_by_taz).pivot_table(index='Taz_num',aggfunc='sum')[['emp_without_palestin_in_taz']]

In [40]:
taz=taz.fillna(0)

taz['total_emp']=taz['emp_not_okev']+taz['emp_okev']+taz['emp_Education']

taz.query('main_secto!="Palestinian"')['total_emp'].sum()-emp_in_jtmt_area_without_mobile

150588.08873364452

## התפלגות ענפי תעסוקה

In [41]:
col=['Indus',
'Com_hotel',
'Business',
'Public',
'agri']

In [42]:
for i in col:
    taz['{}'.format(i)]=taz['{}'.format(i)]*(taz['emp_not_okev']+taz['emp_okev'])

In [43]:
taz['check_emp_sum']=taz[col].sum(axis=1)-(taz['emp_not_okev']+taz['emp_okev'])

taz.query('check_emp_sum>10 |check_emp_sum<-10')

,Taz_name,jeru_metro,in_jerusal,main_secto,SCHN_NAME,ENG_NAME_n,zonetype,Muni_Heb,Sug_Muni,CR_PNIM,highBusine,SCHOOLDIST,Urban,EIProp,poly_puma,F3,F2,F1,agri,Indus,Com_hotel,Business,Public,commuting,ieold,IEProp,perScaled,FreeBuffer,PaidBuffer,Rest_EmpBu,searchtime,walktime,cost,Agg_taz_nu,area,CITYCODE1,CITYCODE2,CITYCODE3,CITYCODE4,codeseq,codeseqCon,county,majunivenr,parktot,superZone,Taz1,slope,REGION,yosh,jerusalem_,geometry,SEA1,SEA2,SEA3,UOA1,UOA2,UOA3,ARA1,ARA2,ARA3,student_chardi_not_gov,student_arab_not_gov,TOA1,TOA2,TOA3,sector_for_chinuc,student,Univ_AR,Univ_SE,Univ_UO,emp_uni,univ,UNIVENRORTHFEMALE,UNIVENRORTHMALE,yeshiva_dorms_pop_15,yeshiva_dorms_pop_20,yeshiva_dorms_pop_25,yeshiva_dorms_pop_sum,emp_from_Yeshiva_student,Yeshiva,Seminar_dorms_pop_15,Seminar_dorms_pop_20,Seminar_dorms_pop_25,Seminar_dorms_pop_sum,emp_from_Seminar_student,Seminar,kollim_demand,add_from_kollim_demand,student_yeshiva_and_kollim,UO_Hi_Ed,emp_UO_Hi_Ed,jew,emp_from_student,emp_Education,aprt_20,pop,pop_0,pop_10,pop_15,pop_20,pop_25,pop_30,pop_35,pop_40,pop_45,pop_5,pop_50,pop_55,pop_60,pop_65,pop_70,pop_75up,hh_size,student_dorms,pop_without_dorms_yeshiva,pop_20_just_from_aprt,pop_25_just_from_aprt,pop_check,pop_15_just_from_aprt,work_age,under_work_age,over_work_age,pop_emp,pop_emp_employed,pop_emp_employed_out_of_jtmt_area,taz_area,okev,emp_okev,emp_not_okev,total_emp,check_emp_sum
Taz_num,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
7101.000,א זעים,1.000,no,Palestinian,0,Judea and Samaria,Judea and Samaria,מטה בנימין,מועצה אזורית,73,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,-0.000,-0.000,-0.000,-0.000,-0.000,0.000,0.000,0.000,1.000,0.000,0.000,0.000,0.000,0.000,0.000,710.000,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,"POLYGON Z ((224716.444 633513.067 0.000, 22478...",0,0,0,0.000,0,0,0.000,0,0,0.000,0.000,0.000,0,0,Palestinian,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0,0.000,0.000,4541.627,18165.473,2276.271,2187.497,2139.905,1782.659,1497.477,1156.696,1028.903,942.565,846.292,2175.581,665.000,531.464,365.438,249.993,159.838,159.893,4.000,0.000,18165.473,1782.659,1497.477,-0.000,2139.905,7033.836,3922.564,569.724,0.000,0.000,0.000,1230701.086,1,-11635.649,0.000,-11635.649,11635.649
7102.000,עזרייה,1.000,no,Palestinian,0,Judea and Samaria,Judea and Samaria,0,0,0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,-0.000,-0.000,-0.000,-0.000,-0.000,0.000,0.000,0.000,1.000,0.000,0.000,0.000,0.000,0.000,0.000,710.000,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,"POLYGON Z ((225184.702 632172.498 0.000, 22526...",0,0,0,0.000,0,0,0.000,0,0,0.000,0.000,0.000,0,0,Palestinian,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0,0.000,0.000,6719.598,27147.814,3034.490,2873.258,2964.632,2647.413,2189.583,1815.245,1522.749,1604.211,1387.367,2998.958,1126.563,954.965,720.177,480.250,362.104,465.849,4.040,0.000,27147.814,2647.413,2189.583,-0.000,2964.632,11320.860,5612.045,1308.203,0.000,0.000,0.000,4125273.428,1,-17215.611,0.000,-17215.611,17215.611
7103.000,אבו דיס,1.000,no,Palestinian,0,Judea and Samaria,Judea and Samaria,0,0,0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,-0.000,-0.000,-0.000,-0.000,-0.000,0.000,0.000,0.000,1.000,0.000,0.000,0.000,0.000,0.000,0.000,710.000,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,"POLYGON Z ((226721.356 630165.442 0.000, 22671...",0,0,0,0.000,0,0,301.000,0,0,0.000,903.000,301.000,0,0,Palestinian,301.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0,0.000,0.000,4283.004,23556.520,3211.393,2802.309,2737.433,2414.852,1908.454,1432.692,1240.765,1151.560,1047.037,3052.805,821.770,610.921,418.094,249.595,220.761,236.079,5.500,0.000,23556.520,2414.852,1908.454,0.000,2737.433,8631.293,5152.285,706.434,0.000,0.000,0.000,6195305.307,1,-10973.055,0.000,-10973.055,10973.055
7104.000,דאר סלאח,1.000,no,Palestinian,0,Judea and Samaria,Judea and Samaria,0,0,0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,-0.000,-0.000,-0.000,-0.000,-0.000,0.000,0.000,0.000,1.000,0.000,0.000,0.000,0.000,0.000,0.000,710.000,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,"POLYGON Z ((223185.882 625323.589 0.000, 22356...",0,0,0,0.000,0,0,0.000,0,0,0.000,0.000,0.000,0,0,Palestinian,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0,0.000,0.000,4034.000,17799.621,2421.159,2138.225,2041.811,1749.867,1400.254,1151.560,990.269,947.919,762.300,2279.692,594.702,462.246,346.009,224.365,128.852,160.389,4.412,0.000,17799.621,1749.867,1400.254,0.000,2041.811,6655.260,3791.678,513.607,0.000,0.000,0.000,10193392.551,1,-10335.108,0.000,-10335.108,10335.108
7912.000,חיזמא,1.000,no,Palestinian,0,Judea and Samaria,Judea and Samaria,מטה בנימין,מועצה אזורית,73,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,-0.000,-0.000,-0.000,-0.000,-0.000,0.000,0.000,0.000,1.000,0.000,0.000,0.000,0.000,0.000,0.000,791.000,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,"POLYGON Z ((229810.587 638412.696 0.000, 22954...",0,0,0,0.000,0,0,0.000,0,0,0.000,0.000,0.000,0,0,Palestinian,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0,0.000,0.000,1165.000,4334.000,523.000,394.000,281.000,295.000,343.000,327.000,286.000,228.000,196.000,475.000,172.000,182.000,180.000,168.000,124.000,160.000,3.720,0.000,4334.000,295.000,343.000,0.000,281.000,1914.000,576.000,452.000,0.000,0.000,0.000,11491442.015,1,-2984.730,0.000,-2984.730,2984.730
7913.000,ענתא,1.000,no,Palestinian,0,Judea and Samaria,Judea and Samaria,0,0,0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,-0.000,-0.000,-0.000,-0.000,-0.000,0.000,0.000,0.000,1.000,0.000,0.000,0.000,0.000,0.000,0.000,791.000,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,"POLYGON Z ((224577.757 636078.136 0.000, 22459...",0,0,0,0.000,0,0,0.000,0,0,0.000,0.000,0.000,0,0,Palestinian,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0,0.000,0.000,2858.911,15632.912,2351.631,1935.234,1800.547,1473.789,1237.585,975.521,875.282,745.712,656.758,2109.075,462.495,406.391,248.540,172.882,113.396,68.074,5.468,0.000,15632.912,1473.789,1237.585,-0.000,1800.547,5608.284,3274.336,354.352,0.000,0.000,0.000,3235312.700,1,-7324.529,0.000,-7324.529,7324.529
8731.000,כפר ניעמה / בלעין,1.000,no,Palestinian,0,Judea and Samaria,Judea and Samaria,0,0,0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,-0.000,-0.000,-0.000,-0.000,-0.000,0.000,0.000,0.000,1.000,0.000,0.000,0.000,0.000,0.000,0.000,873.000,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,"POLYGON Z ((207228.370 651721.540 0.000, 20748...",0,0,0,0.000,0,0,0.000,0,0,0.000,0.000,0.000,0,0,Palestinian,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0,0.000,0.000,1725.322,9834.338,2512.099,1343.338,528.012,526.109,860.516,859.565,567.969,219.291,108.932,2176.740,50.423,27.590,13.795,18.076,11.892,9.989,5.700,0.000,9834.338,526.109,860.516,0.000,528.012,2708.082,1054.121,39.958,0.000,0.000,0.000,38096649.262,1,-4420.276,0.000,-4420.276,4420.276
7954.000,אום א-שראייט מזרח,1.000,no,Palestinian,0,Judea and Samaria,Judea and Samaria,0,0,0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,-0.000,-0.000,-0.000,-0.000,-0.000,0.000,0.000,0.000,1.000,0.000,0.000,0.000,0.000,0.000,0.000,795.000,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,"POLYGON Z ((219777.740 644478.050 0.000, 21987...",0,0,0,0.000,0,0,0.000,0,0,0.000,0.000,0.000,0,0,Palestinian,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0,0.000,0.000,418.809,2303.448,324.663,295.212,271.133,208.042,171.568,143.888,131.140,130.137,101.512,305.541,69.347,55.301,37.300,25.142,17.647,15.876,5.500,0.000,2303.448,208.042,171.568,0.000,271.133,840.193,479.174,58.665,0.000,0.000,0.000,831022.805,1,-1072.988,0.000,-1072.988,1072.988
7250.000,ראס בית ג'אלא,1.000,no,Palestinian,0,Judea and Samaria,Judea and Samaria,גוש עציון,מועצה אזורית,76,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,-0.000,-0.000,-0.000,-0.000,-0.000,0.000,0.000,0.000,1.000,0.000,0.000,0.000,0.000,0.000,0.000,725.000,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,"POLYGON Z ((216640.375 625499.754 0.000, 21673...",0,0,0,0.000,0,0,0.000,0,0,0.000,0.000,0.000,0,0,Palestinian,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0,0.000,0.000,280.012,1052.697,110.354,108.863,110.638,102.401,85.642,72.149,60.645,65.048,60.574,102.046,49.354,39.909,31.104,19.458,16.688,17.824,3.759,0.000,1052.697,102.401,85.642,-0.000,110.638,464.425,213.039,53.970,0.000,0.000,0.000,653687.330,1,-717.392,0.000,-717.392,717.392
7921.000,נבי סמואל,1.000,no,Palestinian,0,Judea and Samaria,Judea and Samaria,מטה בנימין,מועצה אזורית,73,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,-0.000,-0.000,-0.000,-0.000,-0.000,0.000,0.000,0.000,1.000,0.000,0.000,0.000,0.000,0.000,0.000,792.000,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,"POLYGON Z ((216342.778 639816.256 0.000, 21635...",0,0,0,0.000,0,0,0.000,0,0,0.000,0.000,0.000,0,0,Palestinian,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0,0.000,0.000,9696.595,44544.066,5386.230,4932.900,4538.373,4161.923,3574.369,2942.392,2485.201,2358.620,2091.260,4998.570,1723.191,1576.117,1266.860,968.301,682.458,857.302,4.594,0.000,44544.066,4161.923,3574.369,0.000,4538.373,18018.009,8700.296,2508.061,0.000,0.000,0.000,18427817.008,1,-24842.677,0.000,-24842.677,24842.677
7911.000,א ראם,1.000,no,Palestinian,0,Judea and Samaria,Judea and Samaria,0,0,0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,-0.000,-0.000,-0.000,-0.000,-0.000,0.000,0.000,0.000,1.000,0.000,0.000,0.000,0.000,0.000,0.000,791.000,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,"POLYGON Z ((227519.397 641342.026 0.000, 22781...",0,0,0,0.000,0,0,426.667,0,0,0.000,1280.000,426.667,0,0,Palestinian,426.667,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0,0.000,0.000,12476.341,62821.467,8948.320,7519.003,6574.400,5358.788,4965.972,4254.045,3655.671,3371.041,2696.983,8206.962,1978.505,1651.114,1254.612,892.554,687.773,805.723,5.035,0.000,62821.467,5358.788,4965.972,-0.000,6574.400,23827.944,11933.188,2386.050,0.000,0.000,0.000,15302898.413,1,-31964.386,0.000,-31964.386,31964.386
7243.000,קרקפה,1.000,no,Palestinian,0,Judea and Samaria,Judea and Samaria,0,0,0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,-0.000,-0.000,-0.000,-0.000,-0.000,0.000,0.000,0.000,1.000,0.000,0.000,0.000,0.000,0.000,0.000,724.000,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,"POLYGON Z ((219877.168 624622.148 0.000, 22000...",0,0,0,0.000,0,0,0.000,0,0,0.000,0.000,0.000,0,0,Palestinian,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0,0.000,0.000,53.005,199.269,20.889,20.607,20.943,19.384,16.211,13.657,11.480,12.313,11.466,19.317,9.342,7.555,5.888,3.683,3.159,3.374,3.759,0.000,199.269,19.384,16.211,0.000,20.943,87.913,40.327,10.216,0.000,0.000,0.000,789790.998,1,-135.798,0.000,-135.798,135.798
7245.000,בית סאחור,1.000,no,Palestinian,0,Judea and Samaria,Judea and Samaria,גוש עציון,מועצה אזורית,76,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,-0.000,-0.000,-0.000,-0.000,-0.000,0.000,0.000,0.000,1.000,0.000,0.000,0.000,0.000,0.000,0.000,724.000,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,"POLYGON Z ((219734.719 624217.648 0.000, 21973...",0,0,0,0.000,0,0,0.000,0,0,0.000,0.000,0.000,0,0,Palestinian,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0,0.000,0.000,1095.018,4380.073,581.186,464.048,489.278,466.751,376.645,271.220,218.959,245.089,211.750,507.299,171.202,136.061,93.711,60.371,46.855,39.647,4.000,0.000,4380.073,466.751,376.645,0.000,489.278,1724.637,956.029,146.873,0.000,0.000,0.000,3532006.760,1,-2805.437,0.000,-2805.437,2805.437
7240.000,בית ג'אלא מרכז,1.000,no,Palestinian,0,Judea and Samaria,Judea and Samaria,0,0,0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,-0.000,-0.000,-0.000,-0.000,-0.000,0.000,0.000,0.000,1.000,0.000,0.000,0.000,0.000,0.000,0.000,724.000,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,"POLYGON Z ((217381.262 624634.670 0.000, 21745...",0,0,0,0.000,0,0,0.000,0,0,0.000,0.000,0.000,0,0,Palestinian,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0,0.000,0.000,2719.133,10222.482,1071.623,1057.141,1074.381,994.389,831.646,700.623,588.910,631.664,588.220,990.941,479.265,387.550,302.040,188.948,162.054,173.087,3.759,0.000,10222.482,994.389,831.646,0.000,1074.381,4509.919,2068.770,524.088,0.000,0.000,0.000,1514198.138,1,-6966.419,0.000,-6966.419,6966.419
7242.000,אוניברסיטת בית לחם,1.000,no,Palestinian,0,Judea and Samaria,Judea and Samaria,0,0,0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,-0.000,-0.000,-0.000,-0.000,-0.000,0.000,0.000,0.000,1.000,0.000,0.000,0.000,0.000,0.000,0.000,724.000,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,"POLYGON Z ((218722.620 623908.310 0.000, 21873...",0,0,0,0.000,0,0,0.000,0,0,0.000,0.000,0.000,0,0,Palestinian,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0,0.000,0.000,500.850,1882.927,197.387,194.720,197.895,183.161,153.185,129.051,108.474,116.349,108.347,182.526,88.278,71.385,55.634,34.803,29.849,31.882,3.759,0.000,1882.927,183.161,153.185,0.000,197.895,830.703,381.056,96.534,0.000,0.000,0.000,1199852.819,1,-1283.177,0.000,-1283.177,1283.177
7957.000,כפר עקב מזרח,1.000,no,Palestinian,0,Judea and Samaria,Judea and Samaria,מטה בנימין,מועצה אזורית,73,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,-0.000,-0.000,-0.000,-0.000,-0.000,0.000,0.000,0.000,1.000,0.000,0.000,0.000,0.000,0.000,0.000,795.000,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,"POLYGON Z ((220919.410 643805.959 0.000, 22098...",0,0,0,0.000,0,0,0.000,0,0,0.000,0.000,0.000,0,0,Palestinian,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0,0.000,0.000,470.255,2586.401,364.544,331.476,304.438,233.597,192.643,161.563,147.249,146.122,113.982,343.073,77.866,62.094,41.882,28.230,19.814,17.826,5.500,0.000,2586.401,233.597,192.643,-0.000,304.438,943.401,538.036,65.871,0.000,0.000,0.000,1466089.067,1,-1204.793,0.000,-1204.793,1204.793
7231.000,תוקוע,1.000,no,Palestinian,0,Judea and Samaria,Judea and Samaria,0,0,0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,-0.000,-0.000,-0.000,-0.000,-0.000,0.000,0.000,0.000,1.000,0.000,0.000,0.000,0.000,0.000,0.000,723.000,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,"POLYGON Z ((217574.569 620585.802 0.000, 21776...",0,0,0,0.000,0,0,0.000,0,0,0.000,0.000,0.000,0,0,Palestinian,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0,0.000,0.000,1429.602,6246.979,757.525,732.877,558.147,494.610,367.534,436.549,428.881,314.951,224.026,820.515,215.262,237.172,230.599,187.875,122.694,117.764,4.370,0.000,6246.979,494.610,367.534,0.000,558.147,2454.972,1052.757,428.333,0.000,0.000,0.000,28285126.409,1,-3662.641,0.000,-3662.641,3662.641
7256.000,בריכות שלמה,1.000,no,Palestinian,0,Judea and Samaria,Judea and Samaria,0,0,0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,-0.000,-0.000,-0.000,-0.000,-0.000,0.000,0.000,0.000,1.000,0.000,0.000,0.000,0.000,0.000,0.000,725.000,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,"POLYGON Z ((216818.040 622427.130 0.000, 21686...",0,0,0,0.000,0,0,0.000,0,0,0.000,0.000,0.000,0,0,Palestinian,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0,0.000,0.000,1180.398,5158.021,625.475,605.123,460.853,408.390,303.466,360.451,354.119,260.049,184.974,677.485,177.738,195.828,190.401,155.125,101.306,97.236,4.370,0.000,5158.021,408.390,303.466,0.000,460.853,2027.028,869.243,353.667,0.000,0.000,0.000,2281118.978,1,-3024.179,0.000,-3024.179,3024.179

## הוספת סטודנטים אל כמות משקי בית

In [44]:
taz=taz.fillna(0)

taz['hh']=taz['aprt_20']+taz['student_dorms']/1.5

## הוספת תלמידי ישיבה (באזורים לא חרדיים) אל כמות אוכלוסיה,התפלגות גילים ומשקי בית (לכלל תלמידי הישיבה)

In [45]:
taz['hh']=taz['hh']+taz['yeshiva_dorms_pop_sum']

In [46]:
taz.loc[taz['main_secto']!="U_Orthodox",'pop']=taz['pop']+taz['yeshiva_dorms_pop_sum']

taz.loc[taz['main_secto']!="U_Orthodox",'pop_15']=taz['pop_15']+taz['yeshiva_dorms_pop_15']

taz.loc[taz['main_secto']!="U_Orthodox",'pop_20']=taz['pop_20']+taz['yeshiva_dorms_pop_20']

taz.loc[taz['main_secto']!="U_Orthodox",'pop_25']=taz['pop_25']+taz['yeshiva_dorms_pop_25']

## הוספת אוכלוסיה פלסטינאית

In [47]:
path=r'{}\background_files'.format(cwd)
taz_demo_pls_2020=up_load_df(path,'taz_demo_pls_2020_and_pre_growth_till_2050')[['Taz_num','pop_2020']].set_index('Taz_num')

In [48]:

taz.loc[taz['main_secto']=='Palestinian','pop']=taz['pop']+taz_demo_pls_2020['pop_2020']

In [49]:
save_taz_path=r'{}\Intermediates'.format(cwd)
taz.to_excel(r'{}\taz_before_add_geo.xlsx'.format(save_taz_path))